//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from sample.g by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IsampleListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public partial class sampleBaseListener : IsampleListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] sampleParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] sampleParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.ghias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGhias([NotNull] sampleParser.GhiasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.ghias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGhias([NotNull] sampleParser.GhiasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.meghdar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMeghdar([NotNull] sampleParser.MeghdarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.meghdar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMeghdar([NotNull] sampleParser.MeghdarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.wr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWr([NotNull] sampleParser.WrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.wr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWr([NotNull] sampleParser.WrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.entesab"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntesab([NotNull] sampleParser.EntesabContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.entesab"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntesab([NotNull] sampleParser.EntesabContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.scope"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScope([NotNull] sampleParser.ScopeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.scope"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScope([NotNull] sampleParser.ScopeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.ifThenElse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfThenElse([NotNull] sampleParser.IfThenElseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.ifThenElse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfThenElse([NotNull] sampleParser.IfThenElseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.@while"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile([NotNull] sampleParser.WhileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.@while"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile([NotNull] sampleParser.WhileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.forloop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForloop([NotNull] sampleParser.ForloopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.forloop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForloop([NotNull] sampleParser.ForloopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.forsteploop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForsteploop([NotNull] sampleParser.ForsteploopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.forsteploop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForsteploop([NotNull] sampleParser.ForsteploopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.noe"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoe([NotNull] sampleParser.NoeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.noe"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoe([NotNull] sampleParser.NoeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.tarife_moteghir"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTarife_moteghir([NotNull] sampleParser.Tarife_moteghirContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.tarife_moteghir"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTarife_moteghir([NotNull] sampleParser.Tarife_moteghirContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.farakhan"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFarakhan([NotNull] sampleParser.FarakhanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.farakhan"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFarakhan([NotNull] sampleParser.FarakhanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.sakhtar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSakhtar([NotNull] sampleParser.SakhtarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.sakhtar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSakhtar([NotNull] sampleParser.SakhtarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.tabe"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTabe([NotNull] sampleParser.TabeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.tabe"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTabe([NotNull] sampleParser.TabeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.ebarat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEbarat([NotNull] sampleParser.EbaratContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.ebarat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEbarat([NotNull] sampleParser.EbaratContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
