//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from sample.g by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="sampleParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public interface IsampleListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] sampleParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] sampleParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.ghias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGhias([NotNull] sampleParser.GhiasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.ghias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGhias([NotNull] sampleParser.GhiasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.meghdar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMeghdar([NotNull] sampleParser.MeghdarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.meghdar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMeghdar([NotNull] sampleParser.MeghdarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.wr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWr([NotNull] sampleParser.WrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.wr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWr([NotNull] sampleParser.WrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.entesab"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntesab([NotNull] sampleParser.EntesabContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.entesab"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntesab([NotNull] sampleParser.EntesabContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScope([NotNull] sampleParser.ScopeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScope([NotNull] sampleParser.ScopeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.ifThenElse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfThenElse([NotNull] sampleParser.IfThenElseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.ifThenElse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfThenElse([NotNull] sampleParser.IfThenElseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile([NotNull] sampleParser.WhileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile([NotNull] sampleParser.WhileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.forloop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForloop([NotNull] sampleParser.ForloopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.forloop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForloop([NotNull] sampleParser.ForloopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.forsteploop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForsteploop([NotNull] sampleParser.ForsteploopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.forsteploop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForsteploop([NotNull] sampleParser.ForsteploopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.noe"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoe([NotNull] sampleParser.NoeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.noe"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoe([NotNull] sampleParser.NoeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.tarife_moteghir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTarife_moteghir([NotNull] sampleParser.Tarife_moteghirContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.tarife_moteghir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTarife_moteghir([NotNull] sampleParser.Tarife_moteghirContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.farakhan"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFarakhan([NotNull] sampleParser.FarakhanContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.farakhan"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFarakhan([NotNull] sampleParser.FarakhanContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.sakhtar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSakhtar([NotNull] sampleParser.SakhtarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.sakhtar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSakhtar([NotNull] sampleParser.SakhtarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.tabe"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTabe([NotNull] sampleParser.TabeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.tabe"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTabe([NotNull] sampleParser.TabeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="sampleParser.ebarat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEbarat([NotNull] sampleParser.EbaratContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="sampleParser.ebarat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEbarat([NotNull] sampleParser.EbaratContext context);
}
