//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from sample.g by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using System;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public partial class sampleParser : Parser {
	public const int
		STRING=1, INT=2, BOOL=3, DOUBLE=4, BYTE=5, IF=6, TO=7, FOR=8, MFOR=9, 
		STEP=10, THEN=11, BEGIN=12, END=13, WHILE=14, ELSE=15, READ=16, READLINE=17, 
		WRITE=18, MODULE=19, INPUT=20, OUTPUT=21, RETURN=22, TRUE=23, FALSE=24, 
		PLUS=25, OPL=26, OPR=27, MINUS=28, MULTIPLIE=29, DIVIDE=30, ASSIGN=31, 
		PERCENT=32, FACTORIAL=33, POWER=34, AND=35, OR=36, XOR=37, NOT=38, LESSER=39, 
		BIGGER=40, LESSEREQUAL=41, BIGGEREQUAL=42, EQUAL=43, OPPOSITE=44, OPDOT=45, 
		SEPARATOR=46, KAMA=47, ID=48, WS=49, REALCONST=50, INTCONST=51, HEXCONST=52, 
		STRCONST=53, COMMENT1=54, COMMENT2=55;
	public const int
		RULE_prog = 0, RULE_ghias = 1, RULE_meghdar = 2, RULE_wr = 3, RULE_entesab = 4, 
		RULE_scope = 5, RULE_ifThenElse = 6, RULE_while = 7, RULE_forloop = 8, 
		RULE_forsteploop = 9, RULE_noe = 10, RULE_tarife_moteghir = 11, RULE_farakhan = 12, 
		RULE_sakhtar = 13, RULE_tabe = 14, RULE_ebarat = 15;
	public static readonly string[] ruleNames = {
		"prog", "ghias", "meghdar", "wr", "entesab", "scope", "ifThenElse", "while", 
		"forloop", "forsteploop", "noe", "tarife_moteghir", "farakhan", "sakhtar", 
		"tabe", "ebarat"
	};

	private static readonly string[] _LiteralNames = {
		null, "'String'", "'Int'", "'Bool'", "'Double'", "'Byte'", "'If'", "'To'", 
		"'For'", "'Mfor'", "'Step'", "'Then'", "'Begin'", "'End'", "'While'", 
		"'Else'", "'Read'", "'ReadLine'", "'Write'", "'Fanction'", "'Input'", 
		"'Output'", "'Return'", "'True'", "'False'", "'+'", "'('", "')'", "'-'", 
		"'*'", "'/'", "'='", "'%'", "'!'", "'^'", "'And'", "'Or'", "'Xor'", "'Not'", 
		"'<'", "'>'", "'<='", "'>='", "'=='", "'<>'", "':'", "';'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, "STRING", "INT", "BOOL", "DOUBLE", "BYTE", "IF", "TO", "FOR", "MFOR", 
		"STEP", "THEN", "BEGIN", "END", "WHILE", "ELSE", "READ", "READLINE", "WRITE", 
		"MODULE", "INPUT", "OUTPUT", "RETURN", "TRUE", "FALSE", "PLUS", "OPL", 
		"OPR", "MINUS", "MULTIPLIE", "DIVIDE", "ASSIGN", "PERCENT", "FACTORIAL", 
		"POWER", "AND", "OR", "XOR", "NOT", "LESSER", "BIGGER", "LESSEREQUAL", 
		"BIGGEREQUAL", "EQUAL", "OPPOSITE", "OPDOT", "SEPARATOR", "KAMA", "ID", 
		"WS", "REALCONST", "INTCONST", "HEXCONST", "STRCONST", "COMMENT1", "COMMENT2"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "sample.g"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }


	    public CodeRuner.Compailer.Scope SymbolTable = new CodeRuner.Compailer.Scope();
	    public CodeRuner.tabdil_noe typeConverter = new CodeRuner.tabdil_noe();
	public List<string> khata_parser = new List<string>();
	public string cod = "class Program " + Environment.NewLine + "{ " + Environment.NewLine;
	    public int errorCount = 0;
	    
	public void khata_ezaf_kon(string onsor)
	    {
	        if (!string.IsNullOrEmpty(onsor) && !khata_parser.Contains(onsor))
	        {
	            khata_parser.Add(onsor);
	            errorCount++;
	        }
	    }
	    
	    public void khata_pakon()
	    {
	        khata_parser.Clear();
	        errorCount = 0;
	    }

	public sampleParser(ITokenStream input)
		: base(input)
	{
		Interpreter = new ParserATNSimulator(this,_ATN);
	}
	public partial class ProgContext : ParserRuleContext {
		public ITerminalNode Eof() { return GetToken(sampleParser.Eof, 0); }
		public TabeContext[] tabe() {
			return GetRuleContexts<TabeContext>();
		}
		public TabeContext tabe(int i) {
			return GetRuleContext<TabeContext>(i);
		}
		public Tarife_moteghirContext[] tarife_moteghir() {
			return GetRuleContexts<Tarife_moteghirContext>();
		}
		public Tarife_moteghirContext tarife_moteghir(int i) {
			return GetRuleContext<Tarife_moteghirContext>(i);
		}
		public SakhtarContext[] sakhtar() {
			return GetRuleContexts<SakhtarContext>();
		}
		public SakhtarContext sakhtar(int i) {
			return GetRuleContext<SakhtarContext>(i);
		}
		public ProgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prog; } }
		public override void EnterRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.EnterProg(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.ExitProg(this);
		}
	}

	[RuleVersion(0)]
	public ProgContext prog() {
		ProgContext _localctx = new ProgContext(Context, State);
		EnterRule(_localctx, 0, RULE_prog);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 37;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IF) | (1L << FOR) | (1L << MFOR) | (1L << BEGIN) | (1L << WHILE) | (1L << READ) | (1L << READLINE) | (1L << WRITE) | (1L << MODULE) | (1L << RETURN) | (1L << ID))) != 0)) {
				{
				State = 35;
				switch ( Interpreter.AdaptivePredict(TokenStream,0,Context) ) {
				case 1:
					{
					State = 32; tabe();
					}
					break;
				case 2:
					{
					State = 33; tarife_moteghir();
					}
					break;
				case 3:
					{
					State = 34; sakhtar();
					}
					break;
				}
				}
				State = 39;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 40; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GhiasContext : ParserRuleContext {
		public string Csharp = "";
		public ITerminalNode LESSER() { return GetToken(sampleParser.LESSER, 0); }
		public ITerminalNode BIGGER() { return GetToken(sampleParser.BIGGER, 0); }
		public ITerminalNode LESSEREQUAL() { return GetToken(sampleParser.LESSEREQUAL, 0); }
		public ITerminalNode BIGGEREQUAL() { return GetToken(sampleParser.BIGGEREQUAL, 0); }
		public ITerminalNode OPPOSITE() { return GetToken(sampleParser.OPPOSITE, 0); }
		public ITerminalNode EQUAL() { return GetToken(sampleParser.EQUAL, 0); }
		public GhiasContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ghias; } }
		public override void EnterRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.EnterGhias(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.ExitGhias(this);
		}
	}

	[RuleVersion(0)]
	public GhiasContext ghias() {
		GhiasContext _localctx = new GhiasContext(Context, State);
		EnterRule(_localctx, 2, RULE_ghias);
		try {
			State = 54;
			switch (TokenStream.La(1)) {
			case LESSER:
				EnterOuterAlt(_localctx, 1);
				{
				State = 42; Match(LESSER);
				_localctx.Csharp = "<";
				}
				break;
			case BIGGER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 44; Match(BIGGER);
				_localctx.Csharp = ">";
				}
				break;
			case LESSEREQUAL:
				EnterOuterAlt(_localctx, 3);
				{
				State = 46; Match(LESSEREQUAL);
				_localctx.Csharp = "<=";
				}
				break;
			case BIGGEREQUAL:
				EnterOuterAlt(_localctx, 4);
				{
				State = 48; Match(BIGGEREQUAL);
				_localctx.Csharp = ">=";
				}
				break;
			case OPPOSITE:
				EnterOuterAlt(_localctx, 5);
				{
				State = 50; Match(OPPOSITE);
				_localctx.Csharp = "!=";
				}
				break;
			case EQUAL:
				EnterOuterAlt(_localctx, 6);
				{
				State = 52; Match(EQUAL);
				_localctx.Csharp = "==";
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MeghdarContext : ParserRuleContext {
		public string Type = "";
		public string Csharp = "";
		public IToken _ID;
		public IToken _INTCONST;
		public IToken _REALCONST;
		public IToken _STRCONST;
		public ITerminalNode ID() { return GetToken(sampleParser.ID, 0); }
		public ITerminalNode INTCONST() { return GetToken(sampleParser.INTCONST, 0); }
		public ITerminalNode REALCONST() { return GetToken(sampleParser.REALCONST, 0); }
		public ITerminalNode STRCONST() { return GetToken(sampleParser.STRCONST, 0); }
		public ITerminalNode TRUE() { return GetToken(sampleParser.TRUE, 0); }
		public ITerminalNode FALSE() { return GetToken(sampleParser.FALSE, 0); }
		public FarakhanContext farakhan() {
			return GetRuleContext<FarakhanContext>(0);
		}
		public MeghdarContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_meghdar; } }
		public override void EnterRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.EnterMeghdar(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.ExitMeghdar(this);
		}
	}

	[RuleVersion(0)]
	public MeghdarContext meghdar() {
		MeghdarContext _localctx = new MeghdarContext(Context, State);
		EnterRule(_localctx, 4, RULE_meghdar);
		try {
			State = 69;
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 56; _localctx._ID = Match(ID);

				          _localctx.Csharp =  (_localctx._ID!=null?_localctx._ID.Text:null);
				          var symbol = SymbolTable.FindSymbol((_localctx._ID!=null?_localctx._ID.Text:null).ToLower());
				          if(symbol == null)
				          {
				              khata_ezaf_kon("Undefined variable: " + (_localctx._ID!=null?_localctx._ID.Text:null));
				              _localctx.Type =  "no_type";
				          }
				          else 
				          {
				              _localctx.Type =  symbol.SymbolType;
				          }
				      
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 58; _localctx._INTCONST = Match(INTCONST);
				_localctx.Csharp =  (_localctx._INTCONST!=null?_localctx._INTCONST.Text:null); _localctx.Type =  "int";
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 60; _localctx._REALCONST = Match(REALCONST);
				_localctx.Csharp =  (_localctx._REALCONST!=null?_localctx._REALCONST.Text:null); _localctx.Type =  "double";
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 62; _localctx._STRCONST = Match(STRCONST);
				_localctx.Csharp =  (_localctx._STRCONST!=null?_localctx._STRCONST.Text:null); _localctx.Type =  "string";
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 64; Match(TRUE);
				_localctx.Csharp =  "true"; _localctx.Type =  "bool";
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 66; Match(FALSE);
				_localctx.Csharp =  "false"; _localctx.Type =  "bool";
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 68; farakhan();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WrContext : ParserRuleContext {
		public string Csharp = "";
		public EbaratContext _ebarat;
		public IToken _ID;
		public ITerminalNode WRITE() { return GetToken(sampleParser.WRITE, 0); }
		public ITerminalNode OPL() { return GetToken(sampleParser.OPL, 0); }
		public EbaratContext ebarat() {
			return GetRuleContext<EbaratContext>(0);
		}
		public ITerminalNode OPR() { return GetToken(sampleParser.OPR, 0); }
		public ITerminalNode READ() { return GetToken(sampleParser.READ, 0); }
		public ITerminalNode ID() { return GetToken(sampleParser.ID, 0); }
		public ITerminalNode READLINE() { return GetToken(sampleParser.READLINE, 0); }
		public WrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_wr; } }
		public override void EnterRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.EnterWr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.ExitWr(this);
		}
	}

	[RuleVersion(0)]
	public WrContext wr() {
		WrContext _localctx = new WrContext(Context, State);
		EnterRule(_localctx, 6, RULE_wr);
		try {
			State = 91;
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 71; Match(WRITE);
				State = 72; Match(OPL);
				State = 73; _localctx._ebarat = ebarat(0);
				State = 74; Match(OPR);
				_localctx.Csharp =  "System.Console.Write(" + _localctx._ebarat.Csharp + ")";
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 77; Match(READ);
				State = 78; Match(OPL);
				State = 79; _localctx._ID = Match(ID);
				State = 80; Match(OPR);

				          _localctx.Csharp =  (_localctx._ID!=null?_localctx._ID.Text:null) + " = System.Console.Read()";
				          var symbol = SymbolTable.FindSymbol((_localctx._ID!=null?_localctx._ID.Text:null).ToLower());
				          if(symbol == null)
				              khata_ezaf_kon("Undefined variable: " + (_localctx._ID!=null?_localctx._ID.Text:null));
				      
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 82; Match(READLINE);
				State = 83; Match(OPL);
				State = 84; _localctx._ID = Match(ID);
				State = 85; Match(OPR);

				          _localctx.Csharp =  (_localctx._ID!=null?_localctx._ID.Text:null) + " = System.Console.ReadLine()";
				          var symbol = SymbolTable.FindSymbol((_localctx._ID!=null?_localctx._ID.Text:null).ToLower());
				          if(symbol == null)
				              khata_ezaf_kon("Undefined variable: " + (_localctx._ID!=null?_localctx._ID.Text:null));
				      
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 87; Match(READ);
				State = 88; Match(OPL);
				State = 89; Match(OPR);
				_localctx.Csharp =  "System.Console.Read()";
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntesabContext : ParserRuleContext {
		public string Csharp = "";
		public IToken _ID;
		public EbaratContext _ebarat;
		public ITerminalNode ID() { return GetToken(sampleParser.ID, 0); }
		public ITerminalNode ASSIGN() { return GetToken(sampleParser.ASSIGN, 0); }
		public EbaratContext ebarat() {
			return GetRuleContext<EbaratContext>(0);
		}
		public ITerminalNode SEPARATOR() { return GetToken(sampleParser.SEPARATOR, 0); }
		public EntesabContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entesab; } }
		public override void EnterRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.EnterEntesab(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.ExitEntesab(this);
		}
	}

	[RuleVersion(0)]
	public EntesabContext entesab() {
		EntesabContext _localctx = new EntesabContext(Context, State);
		EnterRule(_localctx, 8, RULE_entesab);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 93; _localctx._ID = Match(ID);
			State = 94; Match(ASSIGN);
			State = 95; _localctx._ebarat = ebarat(0);
			State = 96; Match(SEPARATOR);

			          _localctx.Csharp =  (_localctx._ID!=null?_localctx._ID.Text:null) + " = " + _localctx._ebarat.Csharp + ";";
			          var symbol = SymbolTable.FindSymbol((_localctx._ID!=null?_localctx._ID.Text:null).ToLower());
			          if(symbol == null)
			              khata_ezaf_kon("Undefined variable: " + (_localctx._ID!=null?_localctx._ID.Text:null));
			          else if (typeConverter.bareCnoe(_localctx._ebarat.Type, symbol.SymbolType))
			              khata_ezaf_kon("Cannot assign " + _localctx._ebarat.Type + " to " + symbol.SymbolType);
			      
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ScopeContext : ParserRuleContext {
		public string Csharp = "";
		public SakhtarContext _sakhtar;
		public ITerminalNode BEGIN() { return GetToken(sampleParser.BEGIN, 0); }
		public ITerminalNode END() { return GetToken(sampleParser.END, 0); }
		public SakhtarContext[] sakhtar() {
			return GetRuleContexts<SakhtarContext>();
		}
		public SakhtarContext sakhtar(int i) {
			return GetRuleContext<SakhtarContext>(i);
		}
		public ScopeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_scope; } }
		public override void EnterRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.EnterScope(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.ExitScope(this);
		}
	}

	[RuleVersion(0)]
	public ScopeContext scope() {
		ScopeContext _localctx = new ScopeContext(Context, State);
		EnterRule(_localctx, 10, RULE_scope);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 99; Match(BEGIN);

			          _localctx.Csharp += "{";
			          SymbolTable.EnterScope();
			      
			State = 106;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IF) | (1L << FOR) | (1L << MFOR) | (1L << BEGIN) | (1L << WHILE) | (1L << READ) | (1L << READLINE) | (1L << WRITE) | (1L << RETURN) | (1L << ID))) != 0)) {
				{
				{
				State = 101; _localctx._sakhtar = sakhtar();
				_localctx.Csharp += Environment.NewLine + _localctx._sakhtar.Csharp;
				}
				}
				State = 108;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 109; Match(END);

			          _localctx.Csharp += Environment.NewLine + "}";
			          SymbolTable.ExitScope();
			      
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfThenElseContext : ParserRuleContext {
		public string Csharp = "";
		public EbaratContext _ebarat;
		public ScopeContext _scope;
		public IfThenElseContext _ifThenElse;
		public SakhtarContext _sakhtar;
		public ITerminalNode IF() { return GetToken(sampleParser.IF, 0); }
		public EbaratContext ebarat() {
			return GetRuleContext<EbaratContext>(0);
		}
		public ITerminalNode THEN() { return GetToken(sampleParser.THEN, 0); }
		public ScopeContext scope() {
			return GetRuleContext<ScopeContext>(0);
		}
		public ITerminalNode[] ELSE() { return GetTokens(sampleParser.ELSE); }
		public ITerminalNode ELSE(int i) {
			return GetToken(sampleParser.ELSE, i);
		}
		public IfThenElseContext[] ifThenElse() {
			return GetRuleContexts<IfThenElseContext>();
		}
		public IfThenElseContext ifThenElse(int i) {
			return GetRuleContext<IfThenElseContext>(i);
		}
		public ITerminalNode BEGIN() { return GetToken(sampleParser.BEGIN, 0); }
		public ITerminalNode END() { return GetToken(sampleParser.END, 0); }
		public SakhtarContext[] sakhtar() {
			return GetRuleContexts<SakhtarContext>();
		}
		public SakhtarContext sakhtar(int i) {
			return GetRuleContext<SakhtarContext>(i);
		}
		public IfThenElseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifThenElse; } }
		public override void EnterRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.EnterIfThenElse(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.ExitIfThenElse(this);
		}
	}

	[RuleVersion(0)]
	public IfThenElseContext ifThenElse() {
		IfThenElseContext _localctx = new IfThenElseContext(Context, State);
		EnterRule(_localctx, 12, RULE_ifThenElse);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 112; Match(IF);
			State = 113; _localctx._ebarat = ebarat(0);
			State = 114; Match(THEN);
			State = 115; _localctx._scope = scope();

			          if (_localctx._ebarat.Type != "bool")
			              khata_ezaf_kon("Condition must be boolean but has " + _localctx._ebarat.Type);
			          _localctx.Csharp =  "if (" + _localctx._ebarat.Csharp + ")" + Environment.NewLine + _localctx._scope.Csharp;
			      
			State = 123;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					{
					{
					State = 117; Match(ELSE);
					State = 118; _localctx._ifThenElse = ifThenElse();
					_localctx.Csharp += "else " + _localctx.Csharp;
					}
					} 
				}
				State = 125;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			}
			State = 139;
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				{
				State = 126; Match(ELSE);
				State = 127; Match(BEGIN);
				_localctx.Csharp += "else" + Environment.NewLine + "{";
				State = 134;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IF) | (1L << FOR) | (1L << MFOR) | (1L << BEGIN) | (1L << WHILE) | (1L << READ) | (1L << READLINE) | (1L << WRITE) | (1L << RETURN) | (1L << ID))) != 0)) {
					{
					{
					State = 129; _localctx._sakhtar = sakhtar();
					_localctx.Csharp += Environment.NewLine + _localctx._sakhtar.Csharp;
					}
					}
					State = 136;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 137; Match(END);
				_localctx.Csharp += Environment.NewLine + "}";
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WhileContext : ParserRuleContext {
		public string Csharp = "";
		public EbaratContext _ebarat;
		public SakhtarContext _sakhtar;
		public ITerminalNode WHILE() { return GetToken(sampleParser.WHILE, 0); }
		public EbaratContext ebarat() {
			return GetRuleContext<EbaratContext>(0);
		}
		public ITerminalNode BEGIN() { return GetToken(sampleParser.BEGIN, 0); }
		public ITerminalNode END() { return GetToken(sampleParser.END, 0); }
		public SakhtarContext[] sakhtar() {
			return GetRuleContexts<SakhtarContext>();
		}
		public SakhtarContext sakhtar(int i) {
			return GetRuleContext<SakhtarContext>(i);
		}
		public WhileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_while; } }
		public override void EnterRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.EnterWhile(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.ExitWhile(this);
		}
	}

	[RuleVersion(0)]
	public WhileContext @while() {
		WhileContext _localctx = new WhileContext(Context, State);
		EnterRule(_localctx, 14, RULE_while);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 141; Match(WHILE);
			State = 142; _localctx._ebarat = ebarat(0);
			State = 143; Match(BEGIN);

			          if (_localctx._ebarat.Type != "bool")
			              khata_ezaf_kon("Condition must be boolean but has " + _localctx._ebarat.Type);
			          _localctx.Csharp =  "while (" + _localctx._ebarat.Csharp + ")" + Environment.NewLine + "{";
			      
			State = 150;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IF) | (1L << FOR) | (1L << MFOR) | (1L << BEGIN) | (1L << WHILE) | (1L << READ) | (1L << READLINE) | (1L << WRITE) | (1L << RETURN) | (1L << ID))) != 0)) {
				{
				{
				State = 145; _localctx._sakhtar = sakhtar();
				_localctx.Csharp += Environment.NewLine + _localctx._sakhtar.Csharp;
				}
				}
				State = 152;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 153; Match(END);
			_localctx.Csharp += Environment.NewLine + "}";
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ForloopContext : ParserRuleContext {
		public string Csharp = "";
		public IToken _ID;
		public EbaratContext _ebarat;
		public SakhtarContext _sakhtar;
		public ITerminalNode FOR() { return GetToken(sampleParser.FOR, 0); }
		public ITerminalNode ID() { return GetToken(sampleParser.ID, 0); }
		public ITerminalNode ASSIGN() { return GetToken(sampleParser.ASSIGN, 0); }
		public EbaratContext[] ebarat() {
			return GetRuleContexts<EbaratContext>();
		}
		public EbaratContext ebarat(int i) {
			return GetRuleContext<EbaratContext>(i);
		}
		public ITerminalNode TO() { return GetToken(sampleParser.TO, 0); }
		public ITerminalNode THEN() { return GetToken(sampleParser.THEN, 0); }
		public ITerminalNode BEGIN() { return GetToken(sampleParser.BEGIN, 0); }
		public ITerminalNode END() { return GetToken(sampleParser.END, 0); }
		public SakhtarContext[] sakhtar() {
			return GetRuleContexts<SakhtarContext>();
		}
		public SakhtarContext sakhtar(int i) {
			return GetRuleContext<SakhtarContext>(i);
		}
		public ForloopContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_forloop; } }
		public override void EnterRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.EnterForloop(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.ExitForloop(this);
		}
	}

	[RuleVersion(0)]
	public ForloopContext forloop() {
		ForloopContext _localctx = new ForloopContext(Context, State);
		EnterRule(_localctx, 16, RULE_forloop);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 156; Match(FOR);
			State = 157; _localctx._ID = Match(ID);
			State = 158; Match(ASSIGN);
			State = 159; _localctx._ebarat = ebarat(0);
			State = 160; Match(TO);
			State = 161; _localctx._ebarat = ebarat(0);
			State = 162; Match(THEN);
			State = 163; Match(BEGIN);

			          string counter = (_localctx._ID!=null?_localctx._ID.Text:null);
			          _localctx.Csharp =  "for (" + counter + " = " + _localctx._ebarat.Csharp + "; " + counter + " <= " + _localctx._ebarat.Csharp + "; " + counter + "++)" + Environment.NewLine + "{";
			      
			State = 170;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IF) | (1L << FOR) | (1L << MFOR) | (1L << BEGIN) | (1L << WHILE) | (1L << READ) | (1L << READLINE) | (1L << WRITE) | (1L << RETURN) | (1L << ID))) != 0)) {
				{
				{
				State = 165; _localctx._sakhtar = sakhtar();
				_localctx.Csharp += Environment.NewLine + _localctx._sakhtar.Csharp;
				}
				}
				State = 172;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 173; Match(END);
			_localctx.Csharp += Environment.NewLine + "}";
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ForsteploopContext : ParserRuleContext {
		public string Csharp = "";
		public IToken _ID;
		public EbaratContext _ebarat;
		public SakhtarContext _sakhtar;
		public ITerminalNode MFOR() { return GetToken(sampleParser.MFOR, 0); }
		public ITerminalNode ID() { return GetToken(sampleParser.ID, 0); }
		public ITerminalNode ASSIGN() { return GetToken(sampleParser.ASSIGN, 0); }
		public EbaratContext[] ebarat() {
			return GetRuleContexts<EbaratContext>();
		}
		public EbaratContext ebarat(int i) {
			return GetRuleContext<EbaratContext>(i);
		}
		public ITerminalNode TO() { return GetToken(sampleParser.TO, 0); }
		public ITerminalNode THEN() { return GetToken(sampleParser.THEN, 0); }
		public ITerminalNode BEGIN() { return GetToken(sampleParser.BEGIN, 0); }
		public ITerminalNode END() { return GetToken(sampleParser.END, 0); }
		public SakhtarContext[] sakhtar() {
			return GetRuleContexts<SakhtarContext>();
		}
		public SakhtarContext sakhtar(int i) {
			return GetRuleContext<SakhtarContext>(i);
		}
		public ForsteploopContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_forsteploop; } }
		public override void EnterRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.EnterForsteploop(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.ExitForsteploop(this);
		}
	}

	[RuleVersion(0)]
	public ForsteploopContext forsteploop() {
		ForsteploopContext _localctx = new ForsteploopContext(Context, State);
		EnterRule(_localctx, 18, RULE_forsteploop);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 176; Match(MFOR);
			State = 177; _localctx._ID = Match(ID);
			State = 178; Match(ASSIGN);
			State = 179; _localctx._ebarat = ebarat(0);
			State = 180; Match(TO);
			State = 181; _localctx._ebarat = ebarat(0);
			State = 182; Match(THEN);
			State = 183; Match(BEGIN);

			          string counter = (_localctx._ID!=null?_localctx._ID.Text:null);
			          _localctx.Csharp =  "for (" + counter + " = " + _localctx._ebarat.Csharp + "; " + counter + " >= " + _localctx._ebarat.Csharp + "; " + counter + "--)" + Environment.NewLine + "{";
			      
			State = 190;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IF) | (1L << FOR) | (1L << MFOR) | (1L << BEGIN) | (1L << WHILE) | (1L << READ) | (1L << READLINE) | (1L << WRITE) | (1L << RETURN) | (1L << ID))) != 0)) {
				{
				{
				State = 185; _localctx._sakhtar = sakhtar();
				_localctx.Csharp += Environment.NewLine + _localctx._sakhtar.Csharp;
				}
				}
				State = 192;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 193; Match(END);
			_localctx.Csharp += Environment.NewLine + "}";
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NoeContext : ParserRuleContext {
		public string Type = "";
		public string Csharp = "";
		public ITerminalNode STRING() { return GetToken(sampleParser.STRING, 0); }
		public ITerminalNode INT() { return GetToken(sampleParser.INT, 0); }
		public ITerminalNode BOOL() { return GetToken(sampleParser.BOOL, 0); }
		public ITerminalNode DOUBLE() { return GetToken(sampleParser.DOUBLE, 0); }
		public ITerminalNode BYTE() { return GetToken(sampleParser.BYTE, 0); }
		public NoeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_noe; } }
		public override void EnterRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.EnterNoe(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.ExitNoe(this);
		}
	}

	[RuleVersion(0)]
	public NoeContext noe() {
		NoeContext _localctx = new NoeContext(Context, State);
		EnterRule(_localctx, 20, RULE_noe);
		try {
			State = 206;
			switch (TokenStream.La(1)) {
			case STRING:
				EnterOuterAlt(_localctx, 1);
				{
				State = 196; Match(STRING);
				_localctx.Csharp = "string"; _localctx.Type =  "string";
				}
				break;
			case INT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 198; Match(INT);
				_localctx.Csharp = "int"; _localctx.Type =  "int";
				}
				break;
			case BOOL:
				EnterOuterAlt(_localctx, 3);
				{
				State = 200; Match(BOOL);
				_localctx.Csharp = "bool"; _localctx.Type =  "bool";
				}
				break;
			case DOUBLE:
				EnterOuterAlt(_localctx, 4);
				{
				State = 202; Match(DOUBLE);
				_localctx.Csharp = "double"; _localctx.Type =  "double";
				}
				break;
			case BYTE:
				EnterOuterAlt(_localctx, 5);
				{
				State = 204; Match(BYTE);
				_localctx.Csharp = "byte"; _localctx.Type = "byte"
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Tarife_moteghirContext : ParserRuleContext {
		public string Csharp = "";
		public string id = "";
		public IToken _ID;
		public NoeContext _noe;
		public ITerminalNode ID() { return GetToken(sampleParser.ID, 0); }
		public ITerminalNode OPDOT() { return GetToken(sampleParser.OPDOT, 0); }
		public NoeContext noe() {
			return GetRuleContext<NoeContext>(0);
		}
		public ITerminalNode SEPARATOR() { return GetToken(sampleParser.SEPARATOR, 0); }
		public Tarife_moteghirContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tarife_moteghir; } }
		public override void EnterRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.EnterTarife_moteghir(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.ExitTarife_moteghir(this);
		}
	}

	[RuleVersion(0)]
	public Tarife_moteghirContext tarife_moteghir() {
		Tarife_moteghirContext _localctx = new Tarife_moteghirContext(Context, State);
		EnterRule(_localctx, 22, RULE_tarife_moteghir);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 208; _localctx._ID = Match(ID);
			State = 209; Match(OPDOT);
			State = 210; _localctx._noe = noe();
			State = 211; Match(SEPARATOR);

			          _localctx.id =  (_localctx._ID!=null?_localctx._ID.Text:null).ToLower();
			          _localctx.Csharp =  _localctx._noe.Csharp + " " + (_localctx._ID!=null?_localctx._ID.Text:null);
			          if (!SymbolTable.FindInScope(_localctx.id, "variable"))
			              khata_ezaf_kon("Variable redefinition: " + (_localctx._ID!=null?_localctx._ID.Text:null));
			          else
			              SymbolTable.AddSymbol(_localctx.id, _localctx._noe.Type);
			      
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FarakhanContext : ParserRuleContext {
		public string Type = "void";
		public string text = "";
		public string Csharp = "";
		public IToken _ID;
		public ITerminalNode ID() { return GetToken(sampleParser.ID, 0); }
		public ITerminalNode OPL() { return GetToken(sampleParser.OPL, 0); }
		public ITerminalNode OPR() { return GetToken(sampleParser.OPR, 0); }
		public EbaratContext[] ebarat() {
			return GetRuleContexts<EbaratContext>();
		}
		public EbaratContext ebarat(int i) {
			return GetRuleContext<EbaratContext>(i);
		}
		public ITerminalNode[] KAMA() { return GetTokens(sampleParser.KAMA); }
		public ITerminalNode KAMA(int i) {
			return GetToken(sampleParser.KAMA, i);
		}
		public FarakhanContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_farakhan; } }
		public override void EnterRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.EnterFarakhan(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.ExitFarakhan(this);
		}
	}

	[RuleVersion(0)]
	public FarakhanContext farakhan() {
		FarakhanContext _localctx = new FarakhanContext(Context, State);
		EnterRule(_localctx, 24, RULE_farakhan);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 214; _localctx._ID = Match(ID);
			State = 215; Match(OPL);
			State = 224;
			_la = TokenStream.La(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << TRUE) | (1L << FALSE) | (1L << OPL) | (1L << NOT) | (1L << ID) | (1L << REALCONST) | (1L << INTCONST) | (1L << STRCONST))) != 0)) {
				{
				State = 216; ebarat(0);
				State = 221;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==KAMA) {
					{
					{
					State = 217; Match(KAMA);
					State = 218; ebarat(0);
					}
					}
					State = 223;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				}
			}

			State = 226; Match(OPR);

			          _localctx.Csharp =  (_localctx._ID!=null?_localctx._ID.Text:null) + "(...)";
			          var symbol = SymbolTable.FindSymbol((_localctx._ID!=null?_localctx._ID.Text:null).ToLower());
			          if(symbol == null){
			              khata_ezaf_kon("Undefined function: " + (_localctx._ID!=null?_localctx._ID.Text:null));
			              _localctx.Type =  "no_type";
			          }
			          else {
			              _localctx.Type =  symbol.SymbolType;
			              _localctx.text =  (_localctx._ID!=null?_localctx._ID.Text:null);
			          }
			      
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SakhtarContext : ParserRuleContext {
		public string Type = "void";
		public string Csharp = "";
		public EntesabContext _entesab;
		public EbaratContext _ebarat;
		public IfThenElseContext _ifThenElse;
		public WhileContext _while;
		public FarakhanContext _farakhan;
		public WrContext _wr;
		public Tarife_moteghirContext _tarife_moteghir;
		public ForloopContext _forloop;
		public ForsteploopContext _forsteploop;
		public ScopeContext _scope;
		public EntesabContext entesab() {
			return GetRuleContext<EntesabContext>(0);
		}
		public ITerminalNode RETURN() { return GetToken(sampleParser.RETURN, 0); }
		public EbaratContext ebarat() {
			return GetRuleContext<EbaratContext>(0);
		}
		public ITerminalNode SEPARATOR() { return GetToken(sampleParser.SEPARATOR, 0); }
		public IfThenElseContext ifThenElse() {
			return GetRuleContext<IfThenElseContext>(0);
		}
		public WhileContext @while() {
			return GetRuleContext<WhileContext>(0);
		}
		public FarakhanContext farakhan() {
			return GetRuleContext<FarakhanContext>(0);
		}
		public WrContext wr() {
			return GetRuleContext<WrContext>(0);
		}
		public Tarife_moteghirContext tarife_moteghir() {
			return GetRuleContext<Tarife_moteghirContext>(0);
		}
		public ForloopContext forloop() {
			return GetRuleContext<ForloopContext>(0);
		}
		public ForsteploopContext forsteploop() {
			return GetRuleContext<ForsteploopContext>(0);
		}
		public ScopeContext scope() {
			return GetRuleContext<ScopeContext>(0);
		}
		public SakhtarContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sakhtar; } }
		public override void EnterRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.EnterSakhtar(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.ExitSakhtar(this);
		}
	}

	[RuleVersion(0)]
	public SakhtarContext sakhtar() {
		SakhtarContext _localctx = new SakhtarContext(Context, State);
		EnterRule(_localctx, 26, RULE_sakhtar);
		try {
			State = 263;
			switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 229; _localctx._entesab = entesab();
				_localctx.Csharp =  _localctx._entesab.Csharp;
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 232; Match(RETURN);
				State = 233; _localctx._ebarat = ebarat(0);
				State = 234; Match(SEPARATOR);
				_localctx.Csharp =  "return " + _localctx._ebarat.Csharp + ";"; _localctx.Type =  _localctx._ebarat.Type;
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 237; _localctx._ifThenElse = ifThenElse();
				_localctx.Csharp =  _localctx._ifThenElse.Csharp;
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 240; _localctx._while = @while();
				_localctx.Csharp =  _localctx._while.Csharp;
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 243; _localctx._farakhan = farakhan();
				State = 244; Match(SEPARATOR);
				_localctx.Csharp =  _localctx._farakhan.Csharp + ";";
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 247; _localctx._wr = wr();
				State = 248; Match(SEPARATOR);
				_localctx.Csharp =  _localctx._wr.Csharp + ";";
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 251; _localctx._tarife_moteghir = tarife_moteghir();
				_localctx.Csharp =  _localctx._tarife_moteghir.Csharp + ";";
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 254; _localctx._forloop = forloop();
				_localctx.Csharp =  _localctx._forloop.Csharp;
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 257; _localctx._forsteploop = forsteploop();
				_localctx.Csharp =  _localctx._forsteploop.Csharp;
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 260; _localctx._scope = scope();
				_localctx.Csharp =  _localctx._scope.Csharp;
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TabeContext : ParserRuleContext {
		public string Type = "void";
		public string Csharp = "";
		public string name = "";
		public string paramsStr = "";
		public string body = "";
		public IToken _ID;
		public Tarife_moteghirContext _tarife_moteghir;
		public NoeContext _noe;
		public SakhtarContext _sakhtar;
		public ITerminalNode MODULE() { return GetToken(sampleParser.MODULE, 0); }
		public ITerminalNode ID() { return GetToken(sampleParser.ID, 0); }
		public ITerminalNode BEGIN() { return GetToken(sampleParser.BEGIN, 0); }
		public ITerminalNode END() { return GetToken(sampleParser.END, 0); }
		public ITerminalNode INPUT() { return GetToken(sampleParser.INPUT, 0); }
		public ITerminalNode[] OPDOT() { return GetTokens(sampleParser.OPDOT); }
		public ITerminalNode OPDOT(int i) {
			return GetToken(sampleParser.OPDOT, i);
		}
		public ITerminalNode OUTPUT() { return GetToken(sampleParser.OUTPUT, 0); }
		public NoeContext noe() {
			return GetRuleContext<NoeContext>(0);
		}
		public ITerminalNode SEPARATOR() { return GetToken(sampleParser.SEPARATOR, 0); }
		public SakhtarContext[] sakhtar() {
			return GetRuleContexts<SakhtarContext>();
		}
		public SakhtarContext sakhtar(int i) {
			return GetRuleContext<SakhtarContext>(i);
		}
		public Tarife_moteghirContext[] tarife_moteghir() {
			return GetRuleContexts<Tarife_moteghirContext>();
		}
		public Tarife_moteghirContext tarife_moteghir(int i) {
			return GetRuleContext<Tarife_moteghirContext>(i);
		}
		public TabeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tabe; } }
		public override void EnterRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.EnterTabe(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.ExitTabe(this);
		}
	}

	[RuleVersion(0)]
	public TabeContext tabe() {
		TabeContext _localctx = new TabeContext(Context, State);
		EnterRule(_localctx, 28, RULE_tabe);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 265; Match(MODULE);
			State = 266; _localctx._ID = Match(ID);

			          _localctx.name =  (_localctx._ID!=null?_localctx._ID.Text:null).ToLower();
			          if (!SymbolTable.FindInScope(_localctx.name, "function"))
			              khata_ezaf_kon("Function redefinition: " + (_localctx._ID!=null?_localctx._ID.Text:null));
			          SymbolTable.EnterScope();
			      
			State = 277;
			_la = TokenStream.La(1);
			if (_la==INPUT) {
				{
				State = 268; Match(INPUT);
				State = 269; Match(OPDOT);
				State = 273;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				do {
					{
					{
					State = 270; _localctx._tarife_moteghir = tarife_moteghir();
					_localctx.paramsStr += _localctx._tarife_moteghir.Csharp + ", ";
					}
					}
					State = 275;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				} while ( _la==ID );
				}
			}

			State = 285;
			_la = TokenStream.La(1);
			if (_la==OUTPUT) {
				{
				State = 279; Match(OUTPUT);
				State = 280; Match(OPDOT);
				State = 281; _localctx._noe = noe();
				State = 282; Match(SEPARATOR);
				_localctx.Type =  _localctx._noe.Type;
				}
			}

			State = 287; Match(BEGIN);

			          SymbolTable.EnterScope();
			          SymbolTable.AddSymbol(_localctx.name, _localctx.Type);
			          string returnType = string.IsNullOrEmpty(_localctx.Type) || _localctx.Type == "void" ? "void" : _localctx.Type;
			          string methodName = _localctx.name == "main" ? "Main" : _localctx.name;
			          string parameters = _localctx.paramsStr.Length > 0 ? _localctx.paramsStr.TrimEnd(',', ' ') : "";
			          _localctx.Csharp =  (_localctx.name == "main" ? "static " : "") + returnType + " " + methodName + "(" + parameters + ")" + Environment.NewLine + "{";
			      
			State = 294;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IF) | (1L << FOR) | (1L << MFOR) | (1L << BEGIN) | (1L << WHILE) | (1L << READ) | (1L << READLINE) | (1L << WRITE) | (1L << RETURN) | (1L << ID))) != 0)) {
				{
				{
				State = 289; _localctx._sakhtar = sakhtar();

				          _localctx.body += Environment.NewLine + _localctx._sakhtar.Csharp;
				          if(_localctx.Type != "void" && _localctx.Type != _localctx._sakhtar.Type && _localctx._sakhtar.Type != "void")
				              khata_ezaf_kon("Function must return " + _localctx.Type + " but returned " + _localctx._sakhtar.Type);
				      
				}
				}
				State = 296;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 297; Match(END);

			          _localctx.Csharp += _localctx.body + Environment.NewLine + "}";
			          SymbolTable.ExitScope();
			          SymbolTable.ExitScope();
			          if (_localctx.name != "main")
			              SymbolTable.AddSymbol(_localctx.name, _localctx.Type);
			      
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EbaratContext : ParserRuleContext {
		public string Type = "void";
		public string Csharp = "";
		public EbaratContext a;
		public MeghdarContext _meghdar;
		public EbaratContext b;
		public GhiasContext _ghias;
		public ITerminalNode NOT() { return GetToken(sampleParser.NOT, 0); }
		public EbaratContext[] ebarat() {
			return GetRuleContexts<EbaratContext>();
		}
		public EbaratContext ebarat(int i) {
			return GetRuleContext<EbaratContext>(i);
		}
		public ITerminalNode OPL() { return GetToken(sampleParser.OPL, 0); }
		public ITerminalNode OPR() { return GetToken(sampleParser.OPR, 0); }
		public MeghdarContext meghdar() {
			return GetRuleContext<MeghdarContext>(0);
		}
		public ITerminalNode OR() { return GetToken(sampleParser.OR, 0); }
		public ITerminalNode AND() { return GetToken(sampleParser.AND, 0); }
		public GhiasContext ghias() {
			return GetRuleContext<GhiasContext>(0);
		}
		public ITerminalNode PLUS() { return GetToken(sampleParser.PLUS, 0); }
		public ITerminalNode MINUS() { return GetToken(sampleParser.MINUS, 0); }
		public ITerminalNode MULTIPLIE() { return GetToken(sampleParser.MULTIPLIE, 0); }
		public ITerminalNode DIVIDE() { return GetToken(sampleParser.DIVIDE, 0); }
		public ITerminalNode POWER() { return GetToken(sampleParser.POWER, 0); }
		public EbaratContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ebarat; } }
		public override void EnterRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.EnterEbarat(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IsampleListener typedListener = listener as IsampleListener;
			if (typedListener != null) typedListener.ExitEbarat(this);
		}
	}

	[RuleVersion(0)]
	public EbaratContext ebarat() {
		return ebarat(0);
	}

	private EbaratContext ebarat(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		EbaratContext _localctx = new EbaratContext(Context, _parentState);
		EbaratContext _prevctx = _localctx;
		int _startState = 30;
		EnterRecursionRule(_localctx, 30, RULE_ebarat, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 313;
			switch (TokenStream.La(1)) {
			case NOT:
				{
				State = 301; Match(NOT);
				State = 302; _localctx.a = ebarat(2);

				          _localctx.Csharp =  "!" + _localctx.a.Csharp;
				          if(_localctx.a.Type != "bool")
				              khata_ezaf_kon("NOT operator requires boolean operand");
				          _localctx.Type =  "bool";
				      
				}
				break;
			case OPL:
				{
				State = 305; Match(OPL);
				State = 306; _localctx.a = ebarat(0);
				State = 307; Match(OPR);

				          _localctx.Csharp =  "(" + _localctx.a.Csharp + ")";
				          _localctx.Type =  _localctx.a.Type;
				      
				}
				break;
			case TRUE:
			case FALSE:
			case ID:
			case REALCONST:
			case INTCONST:
			case STRCONST:
				{
				State = 310; _localctx._meghdar = meghdar();
				_localctx.Csharp =  _localctx._meghdar.Csharp; _localctx.Type =  _localctx._meghdar.Type;
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.Lt(-1);
			State = 357;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,22,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 355;
					switch ( Interpreter.AdaptivePredict(TokenStream,21,Context) ) {
					case 1:
						{
						_localctx = new EbaratContext(_parentctx, _parentState);
						_localctx.a = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_ebarat);
						State = 315;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 316; Match(OR);
						State = 317; _localctx.b = ebarat(12);

						                    _localctx.Csharp =  _localctx.a.Csharp + " || " + _localctx.b.Csharp;
						                    if(_localctx.a.Type != "bool" || _localctx.b.Type != "bool")
						                        khata_ezaf_kon("OR operator requires boolean operands");
						                    _localctx.Type =  "bool";
						                
						}
						break;
					case 2:
						{
						_localctx = new EbaratContext(_parentctx, _parentState);
						_localctx.a = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_ebarat);
						State = 320;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 321; Match(AND);
						State = 322; _localctx.b = ebarat(11);

						                    _localctx.Csharp =  _localctx.a.Csharp + " && " + _localctx.b.Csharp;
						                    if(_localctx.a.Type != "bool" || _localctx.b.Type != "bool")
						                        khata_ezaf_kon("AND operator requires boolean operands");
						                    _localctx.Type =  "bool";
						                
						}
						break;
					case 3:
						{
						_localctx = new EbaratContext(_parentctx, _parentState);
						_localctx.a = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_ebarat);
						State = 325;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 326; _localctx._ghias = ghias();
						State = 327; _localctx.b = ebarat(10);

						                    _localctx.Csharp =  _localctx.a.Csharp + _localctx._ghias.Csharp + _localctx.b.Csharp;
						                    _localctx.Type =  "bool";
						                
						}
						break;
					case 4:
						{
						_localctx = new EbaratContext(_parentctx, _parentState);
						_localctx.a = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_ebarat);
						State = 330;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 331; Match(PLUS);
						State = 332; _localctx.b = ebarat(9);

						                    _localctx.Csharp =  _localctx.a.Csharp + " + " + _localctx.b.Csharp;
						                    _localctx.Type =  typeConverter.karan_bala(_localctx.a.Type, _localctx.b.Type);
						                
						}
						break;
					case 5:
						{
						_localctx = new EbaratContext(_parentctx, _parentState);
						_localctx.a = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_ebarat);
						State = 335;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 336; Match(MINUS);
						State = 337; _localctx.b = ebarat(8);

						                    _localctx.Csharp =  _localctx.a.Csharp + " - " + _localctx.b.Csharp;
						                    _localctx.Type =  typeConverter.karan_bala(_localctx.a.Type, _localctx.b.Type);
						                
						}
						break;
					case 6:
						{
						_localctx = new EbaratContext(_parentctx, _parentState);
						_localctx.a = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_ebarat);
						State = 340;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 341; Match(MULTIPLIE);
						State = 342; _localctx.b = ebarat(7);

						                    _localctx.Csharp =  _localctx.a.Csharp + " * " + _localctx.b.Csharp;
						                    _localctx.Type =  typeConverter.karan_bala(_localctx.a.Type, _localctx.b.Type);
						                
						}
						break;
					case 7:
						{
						_localctx = new EbaratContext(_parentctx, _parentState);
						_localctx.a = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_ebarat);
						State = 345;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 346; Match(DIVIDE);
						State = 347; _localctx.b = ebarat(6);

						                    _localctx.Csharp =  _localctx.a.Csharp + " / " + _localctx.b.Csharp;
						                    _localctx.Type =  typeConverter.karan_bala(_localctx.a.Type, _localctx.b.Type);
						                
						}
						break;
					case 8:
						{
						_localctx = new EbaratContext(_parentctx, _parentState);
						_localctx.a = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_ebarat);
						State = 350;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 351; Match(POWER);
						State = 352; _localctx.b = ebarat(5);

						                    _localctx.Csharp =  "Math.Pow(" + _localctx.a.Csharp + ", " + _localctx.b.Csharp + ")";
						                    _localctx.Type =  "double";
						                
						}
						break;
					}
					} 
				}
				State = 359;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,22,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 15: return ebarat_sempred((EbaratContext)_localctx, predIndex);
		}
		return true;
	}
	private bool ebarat_sempred(EbaratContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 11);
		case 1: return Precpred(Context, 10);
		case 2: return Precpred(Context, 9);
		case 3: return Precpred(Context, 8);
		case 4: return Precpred(Context, 7);
		case 5: return Precpred(Context, 6);
		case 6: return Precpred(Context, 5);
		case 7: return Precpred(Context, 4);
		}
		return true;
	}

	public static readonly string _serializedATN =
		"\x3\x430\xD6D1\x8206\xAD2D\x4417\xAEF1\x8D80\xAADD\x3\x39\x16B\x4\x2\t"+
		"\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a\t\a\x4\b\t\b\x4\t"+
		"\t\t\x4\n\t\n\x4\v\t\v\x4\f\t\f\x4\r\t\r\x4\xE\t\xE\x4\xF\t\xF\x4\x10"+
		"\t\x10\x4\x11\t\x11\x3\x2\x3\x2\x3\x2\a\x2&\n\x2\f\x2\xE\x2)\v\x2\x3\x2"+
		"\x3\x2\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3"+
		"\x3\x3\x3\x5\x3\x39\n\x3\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3"+
		"\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x5\x4H\n\x4\x3\x5\x3\x5\x3\x5\x3\x5"+
		"\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3"+
		"\x5\x3\x5\x3\x5\x3\x5\x3\x5\x5\x5^\n\x5\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6"+
		"\x3\x6\x3\a\x3\a\x3\a\x3\a\x3\a\a\ak\n\a\f\a\xE\an\v\a\x3\a\x3\a\x3\a"+
		"\x3\b\x3\b\x3\b\x3\b\x3\b\x3\b\x3\b\x3\b\x3\b\a\b|\n\b\f\b\xE\b\x7F\v"+
		"\b\x3\b\x3\b\x3\b\x3\b\x3\b\x3\b\a\b\x87\n\b\f\b\xE\b\x8A\v\b\x3\b\x3"+
		"\b\x5\b\x8E\n\b\x3\t\x3\t\x3\t\x3\t\x3\t\x3\t\x3\t\a\t\x97\n\t\f\t\xE"+
		"\t\x9A\v\t\x3\t\x3\t\x3\t\x3\n\x3\n\x3\n\x3\n\x3\n\x3\n\x3\n\x3\n\x3\n"+
		"\x3\n\x3\n\x3\n\a\n\xAB\n\n\f\n\xE\n\xAE\v\n\x3\n\x3\n\x3\n\x3\v\x3\v"+
		"\x3\v\x3\v\x3\v\x3\v\x3\v\x3\v\x3\v\x3\v\x3\v\x3\v\a\v\xBF\n\v\f\v\xE"+
		"\v\xC2\v\v\x3\v\x3\v\x3\v\x3\f\x3\f\x3\f\x3\f\x3\f\x3\f\x3\f\x3\f\x3\f"+
		"\x3\f\x5\f\xD1\n\f\x3\r\x3\r\x3\r\x3\r\x3\r\x3\r\x3\xE\x3\xE\x3\xE\x3"+
		"\xE\x3\xE\a\xE\xDE\n\xE\f\xE\xE\xE\xE1\v\xE\x5\xE\xE3\n\xE\x3\xE\x3\xE"+
		"\x3\xE\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3"+
		"\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF"+
		"\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3"+
		"\xF\x5\xF\x10A\n\xF\x3\x10\x3\x10\x3\x10\x3\x10\x3\x10\x3\x10\x3\x10\x3"+
		"\x10\x6\x10\x114\n\x10\r\x10\xE\x10\x115\x5\x10\x118\n\x10\x3\x10\x3\x10"+
		"\x3\x10\x3\x10\x3\x10\x3\x10\x5\x10\x120\n\x10\x3\x10\x3\x10\x3\x10\x3"+
		"\x10\x3\x10\a\x10\x127\n\x10\f\x10\xE\x10\x12A\v\x10\x3\x10\x3\x10\x3"+
		"\x10\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3"+
		"\x11\x3\x11\x3\x11\x3\x11\x5\x11\x13C\n\x11\x3\x11\x3\x11\x3\x11\x3\x11"+
		"\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11"+
		"\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11"+
		"\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11"+
		"\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\a\x11\x166\n\x11\f\x11\xE\x11"+
		"\x169\v\x11\x3\x11\x2\x3 \x12\x2\x4\x6\b\n\f\xE\x10\x12\x14\x16\x18\x1A"+
		"\x1C\x1E \x2\x2\x18F\x2\'\x3\x2\x2\x2\x4\x38\x3\x2\x2\x2\x6G\x3\x2\x2"+
		"\x2\b]\x3\x2\x2\x2\n_\x3\x2\x2\x2\f\x65\x3\x2\x2\x2\xEr\x3\x2\x2\x2\x10"+
		"\x8F\x3\x2\x2\x2\x12\x9E\x3\x2\x2\x2\x14\xB2\x3\x2\x2\x2\x16\xD0\x3\x2"+
		"\x2\x2\x18\xD2\x3\x2\x2\x2\x1A\xD8\x3\x2\x2\x2\x1C\x109\x3\x2\x2\x2\x1E"+
		"\x10B\x3\x2\x2\x2 \x13B\x3\x2\x2\x2\"&\x5\x1E\x10\x2#&\x5\x18\r\x2$&\x5"+
		"\x1C\xF\x2%\"\x3\x2\x2\x2%#\x3\x2\x2\x2%$\x3\x2\x2\x2&)\x3\x2\x2\x2\'"+
		"%\x3\x2\x2\x2\'(\x3\x2\x2\x2(*\x3\x2\x2\x2)\'\x3\x2\x2\x2*+\a\x2\x2\x3"+
		"+\x3\x3\x2\x2\x2,-\a)\x2\x2-\x39\b\x3\x1\x2./\a*\x2\x2/\x39\b\x3\x1\x2"+
		"\x30\x31\a+\x2\x2\x31\x39\b\x3\x1\x2\x32\x33\a,\x2\x2\x33\x39\b\x3\x1"+
		"\x2\x34\x35\a.\x2\x2\x35\x39\b\x3\x1\x2\x36\x37\a-\x2\x2\x37\x39\b\x3"+
		"\x1\x2\x38,\x3\x2\x2\x2\x38.\x3\x2\x2\x2\x38\x30\x3\x2\x2\x2\x38\x32\x3"+
		"\x2\x2\x2\x38\x34\x3\x2\x2\x2\x38\x36\x3\x2\x2\x2\x39\x5\x3\x2\x2\x2:"+
		";\a\x32\x2\x2;H\b\x4\x1\x2<=\a\x35\x2\x2=H\b\x4\x1\x2>?\a\x34\x2\x2?H"+
		"\b\x4\x1\x2@\x41\a\x37\x2\x2\x41H\b\x4\x1\x2\x42\x43\a\x19\x2\x2\x43H"+
		"\b\x4\x1\x2\x44\x45\a\x1A\x2\x2\x45H\b\x4\x1\x2\x46H\x5\x1A\xE\x2G:\x3"+
		"\x2\x2\x2G<\x3\x2\x2\x2G>\x3\x2\x2\x2G@\x3\x2\x2\x2G\x42\x3\x2\x2\x2G"+
		"\x44\x3\x2\x2\x2G\x46\x3\x2\x2\x2H\a\x3\x2\x2\x2IJ\a\x14\x2\x2JK\a\x1C"+
		"\x2\x2KL\x5 \x11\x2LM\a\x1D\x2\x2MN\b\x5\x1\x2N^\x3\x2\x2\x2OP\a\x12\x2"+
		"\x2PQ\a\x1C\x2\x2QR\a\x32\x2\x2RS\a\x1D\x2\x2S^\b\x5\x1\x2TU\a\x13\x2"+
		"\x2UV\a\x1C\x2\x2VW\a\x32\x2\x2WX\a\x1D\x2\x2X^\b\x5\x1\x2YZ\a\x12\x2"+
		"\x2Z[\a\x1C\x2\x2[\\\a\x1D\x2\x2\\^\b\x5\x1\x2]I\x3\x2\x2\x2]O\x3\x2\x2"+
		"\x2]T\x3\x2\x2\x2]Y\x3\x2\x2\x2^\t\x3\x2\x2\x2_`\a\x32\x2\x2`\x61\a!\x2"+
		"\x2\x61\x62\x5 \x11\x2\x62\x63\a\x30\x2\x2\x63\x64\b\x6\x1\x2\x64\v\x3"+
		"\x2\x2\x2\x65\x66\a\xE\x2\x2\x66l\b\a\x1\x2gh\x5\x1C\xF\x2hi\b\a\x1\x2"+
		"ik\x3\x2\x2\x2jg\x3\x2\x2\x2kn\x3\x2\x2\x2lj\x3\x2\x2\x2lm\x3\x2\x2\x2"+
		"mo\x3\x2\x2\x2nl\x3\x2\x2\x2op\a\xF\x2\x2pq\b\a\x1\x2q\r\x3\x2\x2\x2r"+
		"s\a\b\x2\x2st\x5 \x11\x2tu\a\r\x2\x2uv\x5\f\a\x2v}\b\b\x1\x2wx\a\x11\x2"+
		"\x2xy\x5\xE\b\x2yz\b\b\x1\x2z|\x3\x2\x2\x2{w\x3\x2\x2\x2|\x7F\x3\x2\x2"+
		"\x2}{\x3\x2\x2\x2}~\x3\x2\x2\x2~\x8D\x3\x2\x2\x2\x7F}\x3\x2\x2\x2\x80"+
		"\x81\a\x11\x2\x2\x81\x82\a\xE\x2\x2\x82\x88\b\b\x1\x2\x83\x84\x5\x1C\xF"+
		"\x2\x84\x85\b\b\x1\x2\x85\x87\x3\x2\x2\x2\x86\x83\x3\x2\x2\x2\x87\x8A"+
		"\x3\x2\x2\x2\x88\x86\x3\x2\x2\x2\x88\x89\x3\x2\x2\x2\x89\x8B\x3\x2\x2"+
		"\x2\x8A\x88\x3\x2\x2\x2\x8B\x8C\a\xF\x2\x2\x8C\x8E\b\b\x1\x2\x8D\x80\x3"+
		"\x2\x2\x2\x8D\x8E\x3\x2\x2\x2\x8E\xF\x3\x2\x2\x2\x8F\x90\a\x10\x2\x2\x90"+
		"\x91\x5 \x11\x2\x91\x92\a\xE\x2\x2\x92\x98\b\t\x1\x2\x93\x94\x5\x1C\xF"+
		"\x2\x94\x95\b\t\x1\x2\x95\x97\x3\x2\x2\x2\x96\x93\x3\x2\x2\x2\x97\x9A"+
		"\x3\x2\x2\x2\x98\x96\x3\x2\x2\x2\x98\x99\x3\x2\x2\x2\x99\x9B\x3\x2\x2"+
		"\x2\x9A\x98\x3\x2\x2\x2\x9B\x9C\a\xF\x2\x2\x9C\x9D\b\t\x1\x2\x9D\x11\x3"+
		"\x2\x2\x2\x9E\x9F\a\n\x2\x2\x9F\xA0\a\x32\x2\x2\xA0\xA1\a!\x2\x2\xA1\xA2"+
		"\x5 \x11\x2\xA2\xA3\a\t\x2\x2\xA3\xA4\x5 \x11\x2\xA4\xA5\a\r\x2\x2\xA5"+
		"\xA6\a\xE\x2\x2\xA6\xAC\b\n\x1\x2\xA7\xA8\x5\x1C\xF\x2\xA8\xA9\b\n\x1"+
		"\x2\xA9\xAB\x3\x2\x2\x2\xAA\xA7\x3\x2\x2\x2\xAB\xAE\x3\x2\x2\x2\xAC\xAA"+
		"\x3\x2\x2\x2\xAC\xAD\x3\x2\x2\x2\xAD\xAF\x3\x2\x2\x2\xAE\xAC\x3\x2\x2"+
		"\x2\xAF\xB0\a\xF\x2\x2\xB0\xB1\b\n\x1\x2\xB1\x13\x3\x2\x2\x2\xB2\xB3\a"+
		"\v\x2\x2\xB3\xB4\a\x32\x2\x2\xB4\xB5\a!\x2\x2\xB5\xB6\x5 \x11\x2\xB6\xB7"+
		"\a\t\x2\x2\xB7\xB8\x5 \x11\x2\xB8\xB9\a\r\x2\x2\xB9\xBA\a\xE\x2\x2\xBA"+
		"\xC0\b\v\x1\x2\xBB\xBC\x5\x1C\xF\x2\xBC\xBD\b\v\x1\x2\xBD\xBF\x3\x2\x2"+
		"\x2\xBE\xBB\x3\x2\x2\x2\xBF\xC2\x3\x2\x2\x2\xC0\xBE\x3\x2\x2\x2\xC0\xC1"+
		"\x3\x2\x2\x2\xC1\xC3\x3\x2\x2\x2\xC2\xC0\x3\x2\x2\x2\xC3\xC4\a\xF\x2\x2"+
		"\xC4\xC5\b\v\x1\x2\xC5\x15\x3\x2\x2\x2\xC6\xC7\a\x3\x2\x2\xC7\xD1\b\f"+
		"\x1\x2\xC8\xC9\a\x4\x2\x2\xC9\xD1\b\f\x1\x2\xCA\xCB\a\x5\x2\x2\xCB\xD1"+
		"\b\f\x1\x2\xCC\xCD\a\x6\x2\x2\xCD\xD1\b\f\x1\x2\xCE\xCF\a\a\x2\x2\xCF"+
		"\xD1\b\f\x1\x2\xD0\xC6\x3\x2\x2\x2\xD0\xC8\x3\x2\x2\x2\xD0\xCA\x3\x2\x2"+
		"\x2\xD0\xCC\x3\x2\x2\x2\xD0\xCE\x3\x2\x2\x2\xD1\x17\x3\x2\x2\x2\xD2\xD3"+
		"\a\x32\x2\x2\xD3\xD4\a/\x2\x2\xD4\xD5\x5\x16\f\x2\xD5\xD6\a\x30\x2\x2"+
		"\xD6\xD7\b\r\x1\x2\xD7\x19\x3\x2\x2\x2\xD8\xD9\a\x32\x2\x2\xD9\xE2\a\x1C"+
		"\x2\x2\xDA\xDF\x5 \x11\x2\xDB\xDC\a\x31\x2\x2\xDC\xDE\x5 \x11\x2\xDD\xDB"+
		"\x3\x2\x2\x2\xDE\xE1\x3\x2\x2\x2\xDF\xDD\x3\x2\x2\x2\xDF\xE0\x3\x2\x2"+
		"\x2\xE0\xE3\x3\x2\x2\x2\xE1\xDF\x3\x2\x2\x2\xE2\xDA\x3\x2\x2\x2\xE2\xE3"+
		"\x3\x2\x2\x2\xE3\xE4\x3\x2\x2\x2\xE4\xE5\a\x1D\x2\x2\xE5\xE6\b\xE\x1\x2"+
		"\xE6\x1B\x3\x2\x2\x2\xE7\xE8\x5\n\x6\x2\xE8\xE9\b\xF\x1\x2\xE9\x10A\x3"+
		"\x2\x2\x2\xEA\xEB\a\x18\x2\x2\xEB\xEC\x5 \x11\x2\xEC\xED\a\x30\x2\x2\xED"+
		"\xEE\b\xF\x1\x2\xEE\x10A\x3\x2\x2\x2\xEF\xF0\x5\xE\b\x2\xF0\xF1\b\xF\x1"+
		"\x2\xF1\x10A\x3\x2\x2\x2\xF2\xF3\x5\x10\t\x2\xF3\xF4\b\xF\x1\x2\xF4\x10A"+
		"\x3\x2\x2\x2\xF5\xF6\x5\x1A\xE\x2\xF6\xF7\a\x30\x2\x2\xF7\xF8\b\xF\x1"+
		"\x2\xF8\x10A\x3\x2\x2\x2\xF9\xFA\x5\b\x5\x2\xFA\xFB\a\x30\x2\x2\xFB\xFC"+
		"\b\xF\x1\x2\xFC\x10A\x3\x2\x2\x2\xFD\xFE\x5\x18\r\x2\xFE\xFF\b\xF\x1\x2"+
		"\xFF\x10A\x3\x2\x2\x2\x100\x101\x5\x12\n\x2\x101\x102\b\xF\x1\x2\x102"+
		"\x10A\x3\x2\x2\x2\x103\x104\x5\x14\v\x2\x104\x105\b\xF\x1\x2\x105\x10A"+
		"\x3\x2\x2\x2\x106\x107\x5\f\a\x2\x107\x108\b\xF\x1\x2\x108\x10A\x3\x2"+
		"\x2\x2\x109\xE7\x3\x2\x2\x2\x109\xEA\x3\x2\x2\x2\x109\xEF\x3\x2\x2\x2"+
		"\x109\xF2\x3\x2\x2\x2\x109\xF5\x3\x2\x2\x2\x109\xF9\x3\x2\x2\x2\x109\xFD"+
		"\x3\x2\x2\x2\x109\x100\x3\x2\x2\x2\x109\x103\x3\x2\x2\x2\x109\x106\x3"+
		"\x2\x2\x2\x10A\x1D\x3\x2\x2\x2\x10B\x10C\a\x15\x2\x2\x10C\x10D\a\x32\x2"+
		"\x2\x10D\x117\b\x10\x1\x2\x10E\x10F\a\x16\x2\x2\x10F\x113\a/\x2\x2\x110"+
		"\x111\x5\x18\r\x2\x111\x112\b\x10\x1\x2\x112\x114\x3\x2\x2\x2\x113\x110"+
		"\x3\x2\x2\x2\x114\x115\x3\x2\x2\x2\x115\x113\x3\x2\x2\x2\x115\x116\x3"+
		"\x2\x2\x2\x116\x118\x3\x2\x2\x2\x117\x10E\x3\x2\x2\x2\x117\x118\x3\x2"+
		"\x2\x2\x118\x11F\x3\x2\x2\x2\x119\x11A\a\x17\x2\x2\x11A\x11B\a/\x2\x2"+
		"\x11B\x11C\x5\x16\f\x2\x11C\x11D\a\x30\x2\x2\x11D\x11E\b\x10\x1\x2\x11E"+
		"\x120\x3\x2\x2\x2\x11F\x119\x3\x2\x2\x2\x11F\x120\x3\x2\x2\x2\x120\x121"+
		"\x3\x2\x2\x2\x121\x122\a\xE\x2\x2\x122\x128\b\x10\x1\x2\x123\x124\x5\x1C"+
		"\xF\x2\x124\x125\b\x10\x1\x2\x125\x127\x3\x2\x2\x2\x126\x123\x3\x2\x2"+
		"\x2\x127\x12A\x3\x2\x2\x2\x128\x126\x3\x2\x2\x2\x128\x129\x3\x2\x2\x2"+
		"\x129\x12B\x3\x2\x2\x2\x12A\x128\x3\x2\x2\x2\x12B\x12C\a\xF\x2\x2\x12C"+
		"\x12D\b\x10\x1\x2\x12D\x1F\x3\x2\x2\x2\x12E\x12F\b\x11\x1\x2\x12F\x130"+
		"\a(\x2\x2\x130\x131\x5 \x11\x4\x131\x132\b\x11\x1\x2\x132\x13C\x3\x2\x2"+
		"\x2\x133\x134\a\x1C\x2\x2\x134\x135\x5 \x11\x2\x135\x136\a\x1D\x2\x2\x136"+
		"\x137\b\x11\x1\x2\x137\x13C\x3\x2\x2\x2\x138\x139\x5\x6\x4\x2\x139\x13A"+
		"\b\x11\x1\x2\x13A\x13C\x3\x2\x2\x2\x13B\x12E\x3\x2\x2\x2\x13B\x133\x3"+
		"\x2\x2\x2\x13B\x138\x3\x2\x2\x2\x13C\x167\x3\x2\x2\x2\x13D\x13E\f\r\x2"+
		"\x2\x13E\x13F\a&\x2\x2\x13F\x140\x5 \x11\xE\x140\x141\b\x11\x1\x2\x141"+
		"\x166\x3\x2\x2\x2\x142\x143\f\f\x2\x2\x143\x144\a%\x2\x2\x144\x145\x5"+
		" \x11\r\x145\x146\b\x11\x1\x2\x146\x166\x3\x2\x2\x2\x147\x148\f\v\x2\x2"+
		"\x148\x149\x5\x4\x3\x2\x149\x14A\x5 \x11\f\x14A\x14B\b\x11\x1\x2\x14B"+
		"\x166\x3\x2\x2\x2\x14C\x14D\f\n\x2\x2\x14D\x14E\a\x1B\x2\x2\x14E\x14F"+
		"\x5 \x11\v\x14F\x150\b\x11\x1\x2\x150\x166\x3\x2\x2\x2\x151\x152\f\t\x2"+
		"\x2\x152\x153\a\x1E\x2\x2\x153\x154\x5 \x11\n\x154\x155\b\x11\x1\x2\x155"+
		"\x166\x3\x2\x2\x2\x156\x157\f\b\x2\x2\x157\x158\a\x1F\x2\x2\x158\x159"+
		"\x5 \x11\t\x159\x15A\b\x11\x1\x2\x15A\x166\x3\x2\x2\x2\x15B\x15C\f\a\x2"+
		"\x2\x15C\x15D\a \x2\x2\x15D\x15E\x5 \x11\b\x15E\x15F\b\x11\x1\x2\x15F"+
		"\x166\x3\x2\x2\x2\x160\x161\f\x6\x2\x2\x161\x162\a$\x2\x2\x162\x163\x5"+
		" \x11\a\x163\x164\b\x11\x1\x2\x164\x166\x3\x2\x2\x2\x165\x13D\x3\x2\x2"+
		"\x2\x165\x142\x3\x2\x2\x2\x165\x147\x3\x2\x2\x2\x165\x14C\x3\x2\x2\x2"+
		"\x165\x151\x3\x2\x2\x2\x165\x156\x3\x2\x2\x2\x165\x15B\x3\x2\x2\x2\x165"+
		"\x160\x3\x2\x2\x2\x166\x169\x3\x2\x2\x2\x167\x165\x3\x2\x2\x2\x167\x168"+
		"\x3\x2\x2\x2\x168!\x3\x2\x2\x2\x169\x167\x3\x2\x2\x2\x19%\'\x38G]l}\x88"+
		"\x8D\x98\xAC\xC0\xD0\xDF\xE2\x109\x115\x117\x11F\x128\x13B\x165\x167";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
